experiment_name: read_classification

input: 
  sample table: /orcd/data/chisholm/001/nvo/projects/24_allison_methylation/Nanopore/MAG_Snakemake/inputs/samples.tsv # inputs/samples.tsv
  adapter_file: inputs/all_illumina_adapters.fa
  cycog_file: inputs/cycog_len.tsv
  nodes_file: /pool001/jmullet/gorgcycogamz20230927/updated_GORG_work/final_database_files/final_ncbi_pro_nodes.dmp
  names_file: /pool001/jmullet/gorgcycogamz20230927/updated_GORG_work/final_database_files/final_ncbi_pro_names.dmp
  fmi_file: /pool001/jmullet/gorgcycogamz20230927/updated_GORG_work/final_database_files/final_MARMICRODB2_virus.fmi
  diamond_file: /pool001/jmullet/blast/cycog6/CyCOG6.dmnd
  

classification_summary:
  # list of genus to extract read count for (remaining genus will be summed into "other_genus")
  genus_list: ['Synechococcus', 'Prochlorococcus', 'unclassified']

scratch directory: /nobackup1b/users/chisholmlab/nvo/24_allison_methylation/Nanopore/ProClassifier
results directory: results
