snakefile: workflow/Snakefile
use-conda: True
conda-frontend: mamba
rerun-incomplete: True
jobs: 5  # number of jobs (samples) to process at once 
latency-wait: 120
keep-going: True
configfile: inputs/config.yaml
keep-incomplete: False
# unlock: True
# dryrun: True

conda-prefix: /orcd/data/chisholm/001/nvo/projects/24_Allison_Classification/ClassificationPipeline/.snakemake_conda_env

cluster: 
  mkdir -p logs/{rule} &&
  sbatch
    --partition={resources.partition}
    --ntasks={resources.tasks}
    --cpus-per-task={resources.cpus_per_task}
    --mem={resources.mem}
    --time={resources.time}
    --job-name={rule}-%j
    --output="logs/{rule}/{wildcards}.out"
    --error="logs/{rule}/{wildcards}.err"

# adjust as needed (increase time and mem if files are large)
default-resources: 
  - time="5-0"  # default time 
  - partition="sched_mit_chisholm"
  - mem=50000  # default memory 
  - cpus_per_task=1  # default: most rules aren't multi-threaded
  - tasks=1

# adjust as needed (increase cpus_per_task and mem if files are large)
set-resources:
  # multi-threaded rules (allocate more cores)
  - run_trim_PE:cpus_per_task=10
  - kaiju_run:cpus_per_task=10
  - blast_reads:cpus_per_task=10

  # memory intensive rules
  - run_trim_PE:mem=100000
  - kaiju_run:mem=100000
  - blast_reads:mem=100000
  - normalize_reads:mem=100000
