[general]
creation_date = "05/16/2024, 21:22:45"
model = "conv_lstm"

[model_params]
size = 256
kmer_len = 9
num_out = 3

[modbases]
mod_bases = [ "21839", "m",]
offset = 0
reverse_signal = false
mod_long_names_0 = "4mC"
mod_long_names_1 = "5mC"
chunk_context_0 = 100
chunk_context_1 = 100
kmer_context_bases_0 = 4
kmer_context_bases_1 = 4
motif = "C"
motif_offset = 0

[refinement]
refine_do_rough_rescale = 1
refine_kmer_center_idx = 6
